[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
      __pycache__
    | \.git
    | setup.py
    | pyproject.toml
    | examples
    | doc
    | bsl/externals/psychopy
    | bsl/externals/pylsl
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
