[tool.black]
line-length = 79
target-version = ['py37']
include = '\.pyi?$'
exclude = '''
(
      __pycache__
    | \.git
    | \doc
    | \examples
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
